### ISSUE TITLE
0.0.9 Flail glitch

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#133]
Graphics glitch in 0.0.9:  glow effect from flail trails from the flail to the edge of the screen briefly when equipping (Linux).  Update:  I could not reproduce the glitch after I started a new game.

**Comment by ChrisNZL** [comment]
Thanks, yeah the flail's ball seems to start at a world 0,0 instantiation point upon first load.

Also noticed creatures (both player and enemy) being hit the first frame the flail starts swinging even though the flail isn't even extended - definitely some placement issues happening.

Flail also has some un-fun issues, like I think it should extend or shrink appropriately to hit a mob near you, rather than being a fixed-length... or the fixed-length should stay, and the damage should be doubled or tripled perhaps.

And there's issue #117 too where picking up the key with the flail swinging results in odd behaviour.

**Comment by ChrisNZL** [comment]
Fixed in v0.0.10.

Additionally:
- You can now about-face with the flail while it's swinging.
- You now spin while jumping with the flail swinging, resulting in very fast flail swings.
