### ISSUE TITLE
Difficulty levels

### ISSUE THREAD

**Issue by drrich** [ChrisNZL/Tallowmere2#237]
Consider adding difficulty levels keeping the danger levels of 0.0.14 (scythboy knockback, zaerie explosion)

**Comment by ChrisNZL** [comment]
For v0.0.15:

- I'm happy with how scythebois deal damage and knock back, don't think they need to be changed.

- Zaerie explosions are remaining intact, but having a Zaerie collide into you immediately after smacking it and having it deal damage is largely unfair, since their buzzsaw weapon is always "on", unlike other enemies that have distinct attack bursts, or projectiles you can prepare for. So with issue #238, Zaeries are now knocked away from you consistently. The constant zig-zag always-on melee damage was just too much.
